apiVersion: v1
kind: PersistentVolume
metadata:
  name: mc-custom-local-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/mizbah_celik/custom
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - gke-mizbah-test-default-pool-7dbea308-4glt
  #         # - gke-mizbah-test-default-pool-7dbea308-dz71
  #         # - gke-mizbah-test-default-pool-7dbea308-tk26 