apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-custom-local-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi