kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: <hz-custom-local-pv / mc-custom-local-pv>
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: </path/to/your/jars>
  nodeAffinity:
    required:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - <YOUR_NODE>
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: < hz-custom-local-pv-claim / mc-custom-local-pv-claim>
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    storage: 1Gi